---
- name: Install Jenkins (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  register: jenkins_installed
  ansible.builtin.apt:
    name: "{{ jenkins_apt_package }}"
    state: present
    update_cache: yes

- name: Register variable to check Jenkins is installed (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  ansible.builtin.set_fact:
    task_install_changed: jenkins_installed.changed

- name: Install Jenkins (CentOS/RedHat)
  when: ansible_os_family == "RedHat"
  register: jenkins_installed
  ansible.builtin.yum:
    name: "{{ jenkins_yum_package }}"
    state: present
    update_cache: yes

- name: Register variable to check Jenkins is installed (CentOS/RedHat)
  when: ansible_os_family == "RedHat"
  ansible.builtin.set_fact:
    task_install_changed: jenkins_installed.changed

# - name: Ensure Jenkins service is started and enabled
#   ansible.builtin.service:
#     name: jenkins
#     state: started
#     enabled: yes

- name: Ensure Jenkins service is started and enabled
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes
